spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:127.0.0.1:3306}/${MYSQL_DATABASE:xx}?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&useUnicode=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: 123123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari-pool
      connection-timeout: 60000
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update